stages:
   - setup
   - test

variables:
   MYSQL_ROOT_PASSWORD: root_password  # MySQL root password for setup
   MYSQL_USER: ticket_test
   MYSQL_PASSWORD: ticket_test_pwd
   MYSQL_DATABASE: ticket_test_db
   CONDA_ENV_NAME: ticket_env

image: continuumio/miniconda3:latest

install_MySQL_Server:
   image: mysql:8.4.0-oraclelinux8  # Install MySQL server
   stage: setup
   script:
      - systemctl start mysql
      - mysql --version
      - mysql -u root -p$MYSQL_ROOT_PASSWORD < create_test_db.sql  # Run a script to create Database
      - mysql -u root -p$MYSQL_ROOT_PASSWORD -e "USE $MYSQL_DATABASE;
      - mysql -u root -p$MYSQL_ROOT_PASSWORD -e "SHOW TABLES;"  # Verify the database

# Define a job to install dependencies with Conda
install_dependencies:
   stage: setup
   script:
      - echo "Setting up Conda environment"
      - conda create -n $CONDA_ENV_NAME python=3.8 -y  # Create Conda environment with Python 3.8 (modify if needed)
      - source activate $CONDA_ENV_NAME  # Activate the environment
      - pip install -r requirements.txt  # Install Python dependencies (make sure to have this file)
      - conda list  # Check installed dependencies

# Define the job to run tests
run_tests:
   stage: test
   script:
      - pip install --upgrade pip
      - echo "Running tests"
      - source activate $CONDA_ENV_NAME  # Activate the Conda environment
      - export TICKET_ENV=test  # Set environment variables
      - export TICKET_MYSQL_USER=$MYSQL_USER
      - export TICKET_MYSQL_PWD=$MYSQL_PASSWORD
      - export TICKET_MYSQL_HOST=localhost
      - export TICKET_MYSQL_DB=$MYSQL_DATABASE
      - python3 -m unittest  # Run the tests
   dependencies:
      # Ensure this job runs after dependencies are installed
      - install_dependencies
      - install_MySQL_Server
   after_script:
      - deactivate  # Deactivate the Conda environment after tests are done
