stages:
   - setup
   - test

variables:
   MYSQL_ROOT_PASSWORD: root_password  # MySQL root password for setup
   MYSQL_USER: ticket_test
   MYSQL_PASSWORD: ticket_test_pwd
   MYSQL_DATABASE: ticket_test_db
   APP_ENV_NAME: ticket_env

services:
  - mysql:8.4.0-oraclelinux8

# Define a job to install dependencies with Conda
install_dependencies:
   image: continuumio/miniconda3:latest
   stage: setup
   script:
      - pip install --upgrade pip
      - conda create -n $APP_ENV_NAME python=3.8 -y  # Create Conda environment with Python 3.8 (modify if needed)
      - source activate $APP_ENV_NAME  # Activate the environment
      - conda env create -f requirements.yml  # Install dependencies
      - conda list  # Check installed dependencies
      - apt-get update
      - mysql --version
      - mysql -u root -p$MYSQL_ROOT_PASSWORD < create_test_db.sql  # Run a script to create Database
      - mysql -u root -p$MYSQL_ROOT_PASSWORD -e "USE $MYSQL_DATABASE;"
      - mysql -u root -p$MYSQL_ROOT_PASSWORD -e "SHOW TABLES;"  # Verify the database

# Define the job to run tests
run_tests:
   stage: test
   script:
      - echo "Running tests"
      - source /opt/conda/etc/profile.d/conda.sh
      - source activate $APP_ENV_NAME  # Activate the environment
      - export TICKET_ENV=test  # Set environment variables
      - export TICKET_MYSQL_USER=$MYSQL_USER
      - export TICKET_MYSQL_PWD=$MYSQL_PASSWORD
      - export TICKET_MYSQL_HOST=localhost
      - export TICKET_MYSQL_DB=$MYSQL_DATABASE
      - python3 -m unittest  # Run the tests
   dependencies:
      # Ensure this job runs after dependencies are installed
      - install_dependencies
   after_script:
      - conda deactivate  # Deactivate the Conda environment after tests are done
