stages:
   - test

variables:
   MYSQL_DATABASE: ticket_test_db
   APP_ENV: 'ai_env'

# Define the job to run tests
run_tests:
   image: continuumio/miniconda3:latest  #  Docker Image to be used
   stage: test
   script:
      - echo "Running tests"
      - source /opt/conda/etc/profile.d/conda.sh
      - conda env create -f requirements.yml --name $APP_ENV  # Install dependencies
      - conda activate $APP_ENV  # Activate the environment
      - export TICKET_ENV=test  # Set environment variables
      - export TICKET_MYSQL_DB=$MYSQL_DATABASE
      - coverage run -m unittest discover  # Run the tests
      - coverage html  # Generate coverage report in an html file
      - conda deactivate
